begin;
do $$declare a uuid:=gen_random_uuid();c uuid:=gen_random_uuid();p uuid:=gen_random_uuid();x uuid:=gen_random_uuid();key uuid:=gen_random_uuid();bid uuid;out jsonb;clock bigint:=(extract(epoch from now())*1000)::bigint+86400000;begin
 insert into auth.users(id,email,email_confirmed_at) values(a,'admin-'||a||'@example.invalid',now()),(c,'client-'||c||'@example.invalid',now()),(p,'provider-'||p||'@example.invalid',now()),(x,'outside-'||x||'@example.invalid',now());
 perform set_config('role','service_role',true);
 perform public.helpme_ensure_profile(a,'admin@example.invalid','Administrador teste','49999999999','customer');perform public.helpme_ensure_profile(c,'client@example.invalid','Cliente teste','49999999999','customer');perform public.helpme_ensure_profile(p,'provider@example.invalid','Prestador teste','49999999999','professional');perform public.helpme_ensure_profile(x,'outside@example.invalid','Outro teste','49999999999','customer');
 insert into helpme.admins values(a);update helpme.profiles set account_status='approved' where id=a;
 begin perform public.helpme_api(c,'/admin','GET');raise exception 'FAILED: unauthorized admin access';exception when sqlstate 'PT403' then null;end;
 begin perform public.helpme_api(c,'/bookings','POST','{}');raise exception 'FAILED: pending booking';exception when sqlstate 'PT403' then null;end;
 perform public.helpme_api(a,'/admin/users/'||c||'/review','POST',jsonb_build_object('status','approved','note','Cadastro de teste aprovado'));
 perform public.helpme_api(a,'/admin/users/'||p||'/review','POST',jsonb_build_object('status','approved','note','Prestador de teste aprovado'));
 perform public.helpme_api(p,'/offers','POST','{"serviceId":"residential","price":18000,"duration":240}');
 perform public.helpme_api(p,'/slots','POST',jsonb_build_object('start',to_timestamp(clock/1000.0),'end',to_timestamp((clock+28800000)/1000.0)));
 out:=public.helpme_api(c,'/bookings','POST',jsonb_build_object('professionalId',p,'serviceId','residential','address','Rua Teste, 100, Maravilha SC','start',to_timestamp(clock/1000.0),'requestKey',key));bid:=(out->>'id')::uuid;
 if (public.helpme_api(c,'/bookings','POST',jsonb_build_object('professionalId',p,'serviceId','residential','address','Rua Teste, 100, Maravilha SC','start',to_timestamp(clock/1000.0),'requestKey',key))->>'id')::uuid<>bid then raise exception 'FAILED: booking idempotence';end if;
 begin perform public.helpme_api(c,'/bookings','POST',jsonb_build_object('professionalId',p,'serviceId','residential','address','Rua Teste, 100, Maravilha SC','start',to_timestamp(clock/1000.0),'requestKey',gen_random_uuid()));raise exception 'FAILED: overlap';exception when sqlstate 'PT409' then null;end;
 perform public.helpme_api(c,'/bookings/'||bid||'/messages','POST',jsonb_build_object('body','Mensagem privada','clientMessageId',key));
 perform public.helpme_api(c,'/bookings/'||bid||'/messages','POST',jsonb_build_object('body','Mensagem privada','clientMessageId',key));
 if jsonb_array_length(public.helpme_api(c,'/bookings/'||bid||'/messages','GET'))<>1 then raise exception 'FAILED: duplicate messages';end if;
 begin perform public.helpme_api(x,'/bookings/'||bid||'/messages','GET');raise exception 'FAILED: chat privacy';exception when sqlstate 'PT404' then null;end;
 perform public.helpme_api(p,'/bookings/'||bid||'/status','POST','{"status":"accepted"}');
 perform public.helpme_api(c,'/checkout_prepare','POST',jsonb_build_object('bookingId',bid));
 begin perform public.helpme_api(c,'/bookings/'||bid||'/status','POST','{"status":"cancelled"}');raise exception 'FAILED: checkout lock';exception when sqlstate 'PT409' then null;end;
 perform public.helpme_api(c,'/checkout_complete','POST',jsonb_build_object('bookingId',bid,'sessionId','cs_test_'||bid,'url','https://checkout.stripe.com/test-fixture'));
 perform public.helpme_confirm_payment('evt_'||bid,'cs_test_'||bid,bid,18000,'brl',false);
 perform public.helpme_confirm_payment('evt_'||bid,'cs_test_'||bid,bid,18000,'brl',false);
 if (select count(*) from helpme.payment_ledger where booking_id=bid)<>1 then raise exception 'FAILED: payment idempotence';end if;
 perform public.helpme_api(a,'/admin/users/'||c||'/review','POST','{"status":"suspended","note":"Suspensão de teste"}');
 begin perform public.helpme_api(c,'/bookings/'||bid||'/messages','POST',jsonb_build_object('body','bloqueada','clientMessageId',gen_random_uuid()));raise exception 'FAILED: suspension';exception when sqlstate 'PT403' then null;end;
 out:=public.helpme_api(a,'/admin','GET');if jsonb_array_length(out->'audit')<3 then raise exception 'FAILED: audit';end if;
 if has_function_privilege('anon','public.helpme_api(uuid,text,text,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.helpme_api(uuid,text,text,jsonb)','EXECUTE') then raise exception 'FAILED: direct RPC exposure';end if;
end $$;
select 'PASS: approval, reservations, private chat, checkout lock, payment idempotence, suspension and audit' result;
rollback;
