begin;
do $$declare c uuid:=gen_random_uuid();p uuid:=gen_random_uuid();other uuid:=gen_random_uuid();a uuid:=gen_random_uuid();bid uuid:=gen_random_uuid();b jsonb;retried jsonb;lockid uuid;oldkey uuid;t bigint:=(extract(epoch from now())*1000)::bigint;
begin
 insert into auth.users(id,email) values(c,'checkout-c@example.invalid'),(p,'checkout-p@example.invalid'),(other,'checkout-other@example.invalid'),(a,'checkout-admin@example.invalid');
 insert into helpme.profiles(id,name,email,phone,role,account_status) values(c,'Cliente','checkout-c@example.invalid','49999999999','customer','approved'),(p,'Prestador','checkout-p@example.invalid','49999999999','professional','approved'),(other,'Outro','checkout-other@example.invalid','49999999999','customer','approved'),(a,'Admin','checkout-admin@example.invalid','49999999999','admin','approved');
 insert into helpme.admins values(a);
 insert into helpme.connected_accounts(professional_id,account_id) values(p,'acct_CheckoutFixture');
 insert into helpme.bookings(id,customer_id,professional_id,service_id,address,start,"end",price,status,payment,request_key,hourly_rate,billing_minutes) values(bid,c,p,'residential','Rua Teste, 100',t-7200000,t-1800000,6750,'completed','unpaid',gen_random_uuid(),4500,90);
 begin perform public.helpme_direct_checkout(other,'/checkout_prepare',jsonb_build_object('bookingId',bid));raise exception 'FAILED ownership';exception when sqlstate 'PT404' then null;end;
 begin perform public.helpme_direct_checkout(a,'/checkout_prepare',jsonb_build_object('bookingId',bid));raise exception 'FAILED admin blocked';exception when sqlstate 'PT403' then null;end;
 b:=public.helpme_direct_checkout(c,'/checkout_prepare',jsonb_build_object('bookingId',bid,'price',1));
 if (b->>'price')::int<>6750 or b->>'connected_account'<>'acct_CheckoutFixture' then raise exception 'FAILED server total';end if;
 lockid:=(b->>'checkout_lock_key')::uuid;oldkey:=(b->>'checkout_key')::uuid;
 begin perform public.helpme_direct_checkout(c,'/checkout_prepare',jsonb_build_object('bookingId',bid));raise exception 'FAILED duplicate lock';exception when sqlstate 'PT409' then null;end;
 begin perform public.helpme_direct_checkout(c,'/checkout_complete',jsonb_build_object('bookingId',bid,'lockKey',gen_random_uuid(),'sessionId','cs_wrong','url','https://checkout.stripe.com/test'));raise exception 'FAILED stale lock';exception when sqlstate 'PT409' then null;end;
 perform public.helpme_direct_checkout(c,'/checkout_complete',jsonb_build_object('bookingId',bid,'lockKey',lockid,'sessionId','cs_fixture','url','https://checkout.stripe.com/test'));
 b:=public.helpme_direct_checkout(c,'/checkout_prepare',jsonb_build_object('bookingId',bid));
 perform public.helpme_direct_checkout(c,'/checkout_release',jsonb_build_object('bookingId',bid,'lockKey',lockid));
 if (select checkout_lock_until from helpme.bookings where id=bid)<=t then raise exception 'FAILED old release cleared new lock';end if;
 retried:=public.helpme_direct_checkout(c,'/checkout_expire',jsonb_build_object('bookingId',bid,'lockKey',b->>'checkout_lock_key','sessionId','cs_fixture'));
 if retried->>'session_id' is not null or (retried->>'checkout_key')::uuid=oldkey then raise exception 'FAILED expired retry';end if;
 perform public.helpme_direct_checkout(c,'/checkout_complete',jsonb_build_object('bookingId',bid,'lockKey',retried->>'checkout_lock_key','sessionId','cs_retry','url','https://checkout.stripe.com/retry'));
 perform public.helpme_confirm_payment('evt_fixture','cs_retry',bid,6750,'brl',false,'acct_CheckoutFixture',1013);
 perform public.helpme_confirm_payment('evt_fixture','cs_retry',bid,6750,'brl',false,'acct_CheckoutFixture',1013);
 if (select payment from helpme.bookings where id=bid)<>'paid' or (select count(*) from helpme.payment_ledger where booking_id=bid)<>1 then raise exception 'FAILED payment confirmation';end if;
 begin perform public.helpme_direct_checkout(c,'/checkout_prepare',jsonb_build_object('bookingId',bid));raise exception 'FAILED paid blocked';exception when sqlstate 'PT409' then null;end;
 if has_function_privilege('anon','public.helpme_direct_checkout(uuid,text,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.helpme_direct_checkout(uuid,text,jsonb)','EXECUTE') then raise exception 'FAILED financial RPC exposure';end if;
end $$;
rollback;
