import {useState} from 'react';
import {dayKey,demoBookings,formatMoney as money,formatTime,monthSummary,zone,type ProviderBooking} from './model';
import './dashboard.css';
type Props={name:string;approved:boolean;bookings:ProviderBooking[];busy:boolean;error?:string;demo?:boolean;onRefresh:()=>void;onLogout:()=>void;onStatus:(id:string,status:string)=>Promise<void>;onConfigure:(type:string,data:unknown)=>Promise<void>;services:{id:string;name:string}[]};
const statusNames:Record<string,string>={requested:'Solicitado',accepted:'Confirmado',completed:'Realizado',cancelled:'Cancelado',rejected:'Recusado'};
const dateLabel=(t:number)=>new Intl.DateTimeFormat('pt-BR',{timeZone:zone,day:'2-digit',month:'short'}).format(t);
const csvCell=(value:unknown)=>'"'+String(value??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';
export default function Dashboard(props:Props){
 const [tab,setTab]=useState('overview'),[month,setMonth]=useState(()=>dayKey(Date.now()).slice(0,7)),[selected,setSelected]=useState(()=>dayKey(Date.now())),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[detail,setDetail]=useState<ProviderBooking|null>(null),[notice,setNotice]=useState(''),[demoRows,setDemoRows]=useState(()=>demoBookings());
 const rows=props.demo?demoRows:props.bookings;
 const summary=monthSummary(rows,month),periodRows=rows.filter(b=>dayKey(b.start).startsWith(month));
 const matches=(b:ProviderBooking)=>(b.customer_name+' '+b.service_name).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'));
 const history=periodRows.filter(b=>b.status==='completed'&&matches(b)&&(filter==='all'||b.payment===filter)).sort((a,b)=>b.start-a.start);
 const [year,monthNumber]=month.split('-').map(Number);
 const monthDate=new Date(Date.UTC(year,monthNumber-1,1,12));
 const title=new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',month:'long',year:'numeric'}).format(monthDate);
 const firstOffset=(new Date(Date.UTC(year,monthNumber-1,1)).getUTCDay()+6)%7;
 const days=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();
 const cells=Array.from({length:Math.ceil((firstOffset+days)/7)*7},(_,i)=>{const day=i-firstOffset+1;return day>=1&&day<=days?`${month}-${String(day).padStart(2,'0')}`:null});
 const dayRows=rows.filter(b=>dayKey(b.start)===selected).sort((a,b)=>a.start-b.start);
 const upcoming=rows.filter(b=>['requested','accepted'].includes(b.status)&&b.start>Date.now()).sort((a,b)=>a.start-b.start).slice(0,4);
 async function act(b:ProviderBooking,status:string){try{if(props.demo){setDemoRows(prev=>prev.map(x=>x.id===b.id?{...x,status}:x));setNotice('Alteração demonstrativa; será descartada ao recarregar.')}else{await props.onStatus(b.id,status);setNotice('Agendamento atualizado.')}setDetail(null)}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível atualizar.')}}
 function move(delta:number){const d=new Date(Date.UTC(year,monthNumber-1+delta,1,12));const next=d.toISOString().slice(0,7);setMonth(next);setSelected(next+'-01')}
 function exportCsv(){const table=[['Data do serviço','Cliente','Serviço','Valor bruto','Pagamento do cliente'],...history.map(b=>[dateLabel(b.start),b.customer_name,b.service_name,(b.price/100).toFixed(2),b.payment==='paid'?'Confirmado':'Pendente'])];const blob=new Blob(['\uFEFF'+table.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`helpme-servicos-${month}.csv`;a.click();URL.revokeObjectURL(url)}
 const list=(bookings:ProviderBooking[])=>bookings.length?bookings.map(b=><button key={b.id} className="appointment" onClick={()=>setDetail(b)}><span className="appointment-date">{dateLabel(b.start)}<small>{formatTime(b.start)}</small></span><span className="appointment-info"><strong>{b.customer_name}</strong><small>{b.service_name}</small></span><span className={'status '+b.status}>{statusNames[b.status]}</span><strong>{money(b.price)}</strong></button>):<p className="empty">Nenhum agendamento neste período.</p>;
 return <div className="provider-shell"><aside className="provider-nav"><a className="logo" href="/">Help<span>.me</span></a><div className="nav-caption">ÁREA DO PRESTADOR</div><nav aria-label="Painel do prestador">{[['overview','Visão geral'],['calendar','Minha agenda'],['history','Serviços realizados'],['payments','Pagamentos'],['settings','Serviços e horários']].map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'active':''} onClick={()=>{setTab(key);setFilter('all')}}><span className="nav-dot"/>{label}</button>)}</nav><div className="provider-account"><div className="avatar">{props.name.charAt(0)}</div><strong>{props.name}</strong><small>{props.approved?'Perfil aprovado':'Aguardando aprovação'}</small><button onClick={props.onLogout}>{props.demo?'Voltar à plataforma':'Sair da conta'}</button></div></aside><div className="provider-main"><div className="provider-top"><span>Maravilha, Santa Catarina</span><span className="badge">{props.demo?'Demonstração':'Área privada'}</span></div>{props.demo&&<div className="demo-banner">Dados fictícios para visualizar o painel. Repasses e alterações abaixo são exemplos, sem movimentação financeira.</div>}<div className="dashboard-heading"><div><div className="eyebrow">SEU TRABALHO, BEM ORGANIZADO</div><h1>{tab==='overview'?`Olá, ${props.name.split(' ')[0]}.`:({calendar:'Minha agenda',history:'Serviços realizados',payments:'Seus pagamentos',settings:'Serviços e horários'} as Record<string,string>)[tab]}</h1><p>{tab==='overview'?'Acompanhe sua agenda e os resultados do seu trabalho.':'Tudo o que você precisa para acompanhar seus serviços.'}</p></div><label className="month-picker">Período<input aria-label="Mês do painel" type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(e.target.value+'-01')}}}/></label></div>{(notice||props.error)&&<div className="notice" role="status">{props.error||notice}</div>}
 {['overview','payments'].includes(tab)&&<div className="kpis"><article><span>Serviços realizados</span><strong>{summary.completed}</strong><small>No mês selecionado</small></article><article><span>Pagamentos dos clientes</span><strong>{money(summary.charged)}</strong><small>Bruto · por data do serviço</small></article><article><span>Repasses recebidos</span><strong>{props.demo?money(summary.received):'Não disponível'}</strong><small>{props.demo?'Exemplo · por data do repasse':'Repasse automático ainda não conectado'}</small></article><article><span>Aguardando pagamento</span><strong>{money(summary.pending)}</strong><small>Confirmados e realizados</small></article></div>}
 {['overview','calendar'].includes(tab)&&<div className="calendar-layout"><section className="panel calendar-panel"><div className="panel-heading"><h2>{title}</h2><div className="actions"><button aria-label="Mês anterior" onClick={()=>move(-1)}>‹</button><button onClick={()=>{setMonth(dayKey(Date.now()).slice(0,7));setSelected(dayKey(Date.now()))}}>Hoje</button><button aria-label="Próximo mês" onClick={()=>move(1)}>›</button></div></div><div className="calendar-week">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((key,i)=>key?<button className={'calendar-day '+(key===selected?'selected ':'')+(key===dayKey(Date.now())?'today':'')} key={key} aria-pressed={key===selected} aria-label={key+' · '+rows.filter(b=>dayKey(b.start)===key).length+' serviços'} onClick={()=>setSelected(key)}><span>{Number(key.slice(-2))}</span><div>{rows.filter(b=>dayKey(b.start)===key).slice(0,3).map(b=><small className={'event-dot '+b.status} key={b.id} title={statusNames[b.status]}/>)}</div></button>:<span className="calendar-blank" key={'blank'+i}/>)}</div><div className="calendar-legend"><span><i className="event-dot accepted"/> Confirmado</span><span><i className="event-dot requested"/> Solicitação</span><span><i className="event-dot completed"/> Realizado</span></div></section><section className="panel day-panel"><div className="panel-heading"><h2>{new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'numeric',month:'long'}).format(new Date(selected+'T12:00:00Z'))}</h2><span>{dayRows.length} serviços</span></div>{list(dayRows)}<p className="calendar-footnote">Horários de Brasília (America/Sao_Paulo).</p></section></div>}
 {tab==='overview'&&<section className="panel"><div className="panel-heading"><h2>Próximos serviços</h2><button onClick={()=>setTab('calendar')}>Ver agenda</button></div>{list(upcoming)}{rows.some(b=>b.status==='requested')&&<p className="pending-callout">Você tem {rows.filter(b=>b.status==='requested').length} solicitações aguardando resposta. Selecione o pedido na agenda para responder.</p>}</section>}
 {tab==='history'&&<section className="panel"><div className="panel-heading"><h2>Histórico do mês</h2><button disabled={!history.length} onClick={exportCsv}>Exportar CSV</button></div><div className="table-filters"><label>Buscar cliente ou serviço<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Digite para buscar"/></label><label>Pagamento<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="paid">Confirmados</option><option value="unpaid">Pendentes</option></select></label></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Cliente / serviço</th><th>Valor bruto</th><th>Pagamento do cliente</th><th>Detalhes</th></tr></thead><tbody>{history.map(b=><tr key={b.id}><td>{dateLabel(b.start)}<small>{formatTime(b.start)}</small></td><td><strong>{b.customer_name}</strong><small>{b.service_name}</small></td><td>{money(b.price)}</td><td><span className={'status '+(b.payment==='paid'?'completed':'requested')}>{b.payment==='paid'?'Confirmado':'Pendente'}</span></td><td><button onClick={()=>setDetail(b)}>Ver serviço</button></td></tr>)}</tbody></table></div>{!history.length&&<p className="empty">Nenhum serviço realizado para os filtros selecionados.</p>}</section>}
 {tab==='payments'&&<section className="panel"><h2>Pagamentos por serviço</h2><p className="financial-note">Pagamento do cliente confirma a cobrança do serviço. Repasse recebido significa dinheiro destinado ao prestador. {props.demo?'Os repasses abaixo são exemplos fictícios, com valores ilustrativos.':'A integração de repasses ainda não está disponível; não existe saldo liberado para saque neste painel.'}</p><div className="table-wrap"><table><thead><tr><th>Serviço / cliente</th><th>Valor bruto</th><th>Pagamento do cliente</th><th>Repasse ao prestador</th><th>Data do repasse</th></tr></thead><tbody>{periodRows.filter(b=>['accepted','completed'].includes(b.status)).map(b=><tr key={b.id}><td><strong>{b.customer_name}</strong><small>{b.service_name} · {dateLabel(b.start)}</small></td><td>{money(b.price)}</td><td><span className={'status '+(b.payment==='paid'?'completed':'requested')}>{b.payment==='paid'?'Confirmado':'Pendente'}</span></td><td>{b.providerPaidCents!==undefined?money(b.providerPaidCents):'Não informado'}</td><td>{b.providerPaidAt?dateLabel(b.providerPaidAt):'—'}</td></tr>)}</tbody></table></div>{!periodRows.filter(b=>['accepted','completed'].includes(b.status)).length&&<p className="empty">Nenhum pagamento vinculado a serviços neste mês.</p>}</section>}
 {tab==='settings'&&<div className="calendar-layout"><section className="panel"><h2>Configurar serviço</h2><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(props.demo){setNotice('Configuração demonstrativa. Nenhuma oferta foi salva.');return}props.onConfigure('offers',{serviceId:f.serviceId,price:Math.round(Number(f.price)*100),duration:Number(f.duration)}).then(()=>setNotice('Oferta salva.')).catch(e=>setNotice(e.message))}}><label>Serviço<select name="serviceId">{props.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Preço (R$)<input name="price" type="number" min="1" step="0.01" defaultValue="180" required/></label><label>Duração (minutos)<input name="duration" type="number" min="30" max="720" defaultValue="240" required/></label><button className="primary" disabled={props.busy}>Salvar oferta</button></form></section><section className="panel"><h2>Adicionar disponibilidade</h2><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(props.demo){setNotice('Configuração demonstrativa. Nenhum horário foi salvo.');return}props.onConfigure('slots',{start:new Date(String(f.start)).toISOString(),end:new Date(String(f.end)).toISOString()}).then(()=>setNotice('Disponibilidade salva.')).catch(e=>setNotice(e.message))}}><label>Início<input type="datetime-local" name="start" required/></label><label>Fim<input type="datetime-local" name="end" required/></label><button className="primary" disabled={props.busy}>Adicionar intervalo</button></form></section></div>}
 <div className="dashboard-footer"><span>{props.demo?'Prévia com dados fictícios':'Dados da sua conta'} · Help.me</span><button disabled={props.busy} onClick={()=>{props.onRefresh();setNotice(props.demo?'Você está visualizando dados de demonstração.':'Atualizando registros…')}}>Atualizar dados</button></div>
 {detail&&<div className="detail-overlay"><section className="detail-dialog" role="dialog" aria-modal="true" aria-label="Detalhes do serviço" onKeyDown={e=>{if(e.key==='Escape')setDetail(null);if(e.key==='Tab'){const targets=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select'));const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><button autoFocus className="detail-close" aria-label="Fechar detalhes" onClick={()=>setDetail(null)}>×</button><span className={'status '+detail.status}>{statusNames[detail.status]}</span><h2>{detail.service_name}</h2><p>{detail.customer_name}</p><dl><dt>Quando</dt><dd>{dateLabel(detail.start)} · {formatTime(detail.start)}{detail.end?' – '+formatTime(detail.end):''}</dd><dt>Endereço</dt><dd>{detail.address||'Disponível após o aceite'}</dd><dt>Valor do serviço</dt><dd>{money(detail.price)}</dd><dt>Pagamento do cliente</dt><dd>{detail.payment==='paid'?'Confirmado':'Pendente'}</dd></dl><div className="actions">{detail.status==='requested'&&<><button className="primary" disabled={props.busy} onClick={()=>act(detail,'accepted')}>Aceitar serviço</button><button disabled={props.busy} onClick={()=>act(detail,'rejected')}>Recusar</button></>}{detail.status==='accepted'&&<button className="primary" disabled={props.busy||!!detail.end&&detail.end>Date.now()} onClick={()=>act(detail,'completed')}>Marcar como realizado</button>}<button onClick={()=>setDetail(null)}>Fechar</button></div></section></div>}
 </div></div>
}
