import {test} from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('chat privado, persistente, idempotente e disponibilidade sem conflitos',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'helpme-chat-'));const dbPath=join(dir,'test.sqlite');
 const {app,db}=createApp({dbPath});const customer=request.agent(app),pro=request.agent(app),outsider=request.agent(app);
 const post=(agent,path,body)=>agent.post('/api'+path).set('Origin','http://localhost:5173').send(body);
 const register=(agent,email,role)=>post(agent,'/auth/register',{name:'Teste do chat',email,role,password:'senha-teste-forte-1234',phone:'49999999999'});
 const cr=await register(customer,'chatcustomer@example.com','customer');const pr=await register(pro,'chatpro@example.com','professional');await register(outsider,'chatother@example.com','customer');
 const pid=pr.body.user.id;db.prepare('UPDATE users SET approved=1 WHERE id=?').run(pid);
 await post(pro,'/offers',{serviceId:'residential',price:18000,duration:120});
 const start=Math.ceil((Date.now()+86400000)/1800000)*1800000;
 await post(pro,'/slots',{start:new Date(start).toISOString(),end:new Date(start+4*3600000).toISOString()});
 const before=await customer.get(`/api/professionals/${pid}/availability?serviceId=residential`);assert.equal(before.status,200);assert(before.body.some(s=>s.start===start));
 const booking=await post(customer,'/bookings',{professionalId:pid,serviceId:'residential',address:'Rua Teste, 100, Maravilha SC',start:new Date(start).toISOString(),requestKey:randomUUID()});assert.equal(booking.status,201);const id=booking.body.id;
 const after=await customer.get(`/api/professionals/${pid}/availability?serviceId=residential`);assert(!after.body.some(s=>s.start<start+120*60000&&s.end>start));
 assert.equal((await request(app).get('/api/bookings/'+id+'/messages')).status,401);
 assert.equal((await outsider.get('/api/bookings/'+id+'/messages')).status,404);
 const nonce=randomUUID(),body='<script>alert(1)</script> Você traz os materiais?';
 const first=await post(customer,'/bookings/'+id+'/messages',{body,clientMessageId:nonce,sender_id:pid});assert.equal(first.status,201);assert.equal(first.body.sender_id,cr.body.user.id);
 const retry=await post(customer,'/bookings/'+id+'/messages',{body,clientMessageId:nonce});assert.equal(retry.body.id,first.body.id);
 assert.equal((await post(outsider,'/bookings/'+id+'/messages',{body:'invasão',clientMessageId:randomUUID()})).status,404);
 assert.equal((await post(customer,'/bookings/'+id+'/messages',{body:' ',clientMessageId:randomUUID()})).status,400);
 assert.equal((await post(customer,'/bookings/'+id+'/messages',{body:'x'.repeat(2001),clientMessageId:randomUUID()})).status,400);
 assert.equal((await post(pro,'/bookings/'+id+'/messages',{body:'Podemos combinar os materiais.',clientMessageId:randomUUID()})).status,201);
 const received=await pro.get('/api/bookings/'+id+'/messages');assert.equal(received.body.length,2);assert.equal(received.body[0].body,body);
 const incremental=await customer.get('/api/bookings/'+id+'/messages?after='+first.body.seq);assert.equal(incremental.body.length,1);
 assert.equal((await customer.get('/api/bookings/'+randomUUID()+'/messages')).status,404);
 const plan=db.prepare('EXPLAIN QUERY PLAN SELECT seq FROM messages WHERE booking_id=? AND seq>? ORDER BY seq LIMIT 100').all(id,0);assert(plan.some(row=>row.detail.includes('idx_messages_booking_seq')));
 db.close();const reopened=createApp({dbPath});assert.equal(reopened.db.prepare('SELECT COUNT(*) n FROM messages').get().n,2);reopened.db.close();rmSync(dir,{recursive:true,force:true});
});
