import {test} from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import Stripe from 'stripe';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';
const origin='http://localhost:5173';
test('cadastro, autorização, reserva e bloqueio do checkout local sem Connect',async()=>{
 let checkoutCalls=0;
 const sdk=new Stripe('sk_test_fixture');
 const {app,db}=createApp({dbPath:':memory:',webhookSecret:'whsec_fixture',stripeClient:{webhooks:sdk.webhooks,checkout:{sessions:{create:async input=>{checkoutCalls++;assert.equal(input.line_items[0].price_data.unit_amount,18000);return {id:'cs_test_fixture',url:'https://checkout.stripe.com/test-fixture'}}}}}});
 const c=request.agent(app),p=request.agent(app),other=request.agent(app);
 const post=(a,path,body)=>a.post('/api'+path).set('Origin',origin).send(body);
 const reg=(a,email,role)=>post(a,'/auth/register',{name:'Pessoa teste',email,phone:'49999999999',password:'senha-forte-12345',role});
 const cr=await reg(c,'cliente@example.com','customer');assert.equal(cr.status,200);
 const pr=await reg(p,'profissional@example.com','professional');assert.equal(pr.status,200);const pid=pr.body.user.id;
 await reg(other,'outro@example.com','customer');
 assert.equal((await post(p,'/offers',{serviceId:'residential',price:18000,duration:240})).status,200);
 const start=Date.now()+86400000;
 assert.equal((await post(p,'/slots',{start:new Date(start).toISOString(),end:new Date(start+8*3600000).toISOString()})).status,200);
 const input={professionalId:pid,serviceId:'residential',address:'Rua de Teste, 100, Maravilha SC',start:new Date(start).toISOString(),requestKey:randomUUID()};
 assert.equal((await post(c,'/bookings',input)).status,403);
 db.prepare("UPDATE users SET approved=1 WHERE role='customer' OR id=?").run(pid);
 const first=await post(c,'/bookings',input);assert.equal(first.status,201);const id=first.body.id;
 assert.equal((await post(c,'/bookings',input)).body.id,id);
 assert.equal((await post(other,'/bookings',{...input,requestKey:randomUUID(),start:new Date(start+3600000).toISOString()})).status,409);
 assert.equal((await other.get('/api/bookings')).body.length,0);
 assert.equal((await p.get('/api/bookings')).body[0].address,null);
 assert.equal((await post(other,'/bookings/'+id+'/status',{status:'accepted'})).status,404);
 assert.equal((await post(p,'/bookings/'+id+'/status',{status:'accepted'})).status,200);
 assert.equal((await p.get('/api/bookings')).body[0].address,input.address);
 assert.equal((await post(c,'/checkout',{bookingId:id})).status,503);assert.equal(checkoutCalls,0);
 assert.equal((await request(app).post('/api/auth/register').send({})).status,403);
 db.close();
});
test('Stripe ausente é declarado e não simula pagamento',async()=>{const {app,db}=createApp({dbPath:':memory:'});assert.equal((await request(app).get('/api/config')).body.stripeConfigured,false);assert.equal((await request(app).post('/api/stripe/webhook')).status,503);db.close()});
