import Checkout from '../../components/Checkout';
import {canPay} from '../../lib/checkout';
import {Avatar} from '../../components/ProfilePhoto';
import {hourlyTotal} from '../../lib/routes';
import {ProfileDialog,Rating,ReviewForm,reputation} from '../../components/Reputation';
import {apiFetch} from '../../lib/backend';
import {useEffect,useState} from 'react';
import ServiceChat from '../../components/ServiceChat';
import {demoBookings,formatMoney as money,zone} from '../professional-dashboard/model';
import './customer.css';
import {categoryOf,filterOffers} from './search';
type Offer={professional_id:string;service_id:string;professional_name:string;service_name:string;price:number;duration:number;rating_average?:number|null;review_count?:number;bio?:string;skills?:string;photo_url?:string};
type Booking={id:string;service_name:string;professional_name:string;customer_name:string;status:string;payment:string;start:number;end?:number;hourly_rate?:number;billing_minutes?:number;price:number;address:string|null;session_id:string|null};
type Props={user:{id:string;name:string;email?:string;phone?:string;approved?:boolean;accountStatus?:string}|null;offers:Offer[];bookings:Booking[];services:{id:string;name:string}[];busy:boolean;error:string;catalogError?:string;catalogBusy?:boolean;onRetryCatalog?:()=>void;stripe:boolean;demo?:boolean;onRegister:()=>void;onLogin:()=>void;onLogout:()=>void;onBook:(input:unknown)=>Promise<void>;onCancel:(id:string)=>Promise<void>;onPay:(id:string)=>Promise<void>};
const date=(n:number)=>new Intl.DateTimeFormat('pt-BR',{timeZone:zone,day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(n);
const demoOffers:Offer[]=[{professional_id:'demo-p1',service_id:'residential',professional_name:'Prestador exemplo A',service_name:'Limpeza residencial',price:4500,duration:240},{professional_id:'demo-p2',service_id:'deep',professional_name:'Prestador exemplo B',service_name:'Limpeza pesada',price:4333,duration:360},{professional_id:'demo-p3',service_id:'residential',professional_name:'Prestador exemplo C',service_name:'Limpeza residencial',price:5000,duration:240},{professional_id:'demo-p4',service_id:'babysitting',professional_name:'Prestadora exemplo D',service_name:'Babá',price:3000,duration:240}];
const status:Record<string,string>={requested:'Aguardando aceite',accepted:'Confirmado',completed:'Realizado',cancelled:'Cancelado',rejected:'Recusado'};
export default function CustomerArea(p:Props){
 const [paying,setPaying]=useState<Booking|null>(null);
 const paymentReturn=new URLSearchParams(location.search).get('payment');
 const returnedBooking=new URLSearchParams(location.search).get('booking');
 const returnRow=bookingsForReturn(p,returnedBooking);
 const [publicProfile,setPublicProfile]=useState<Offer|null>(null),[reviewing,setReviewing]=useState(''),[reviewed,setReviewed]=useState<string[]>([]),[reviewsLoaded,setReviewsLoaded]=useState(!!p.demo);
 useEffect(()=>{if(!p.user||p.demo)return;let active=true;reputation('/reviews/mine').then(rows=>{if(active){setReviewed(rows.map((r:{booking_id:string})=>r.booking_id));setReviewsLoaded(true)}}).catch(e=>{if(active)setNotice(e.message)});return()=>{active=false}},[p.user,p.demo]);
 const [tab,setTab]=useState(()=>new URLSearchParams(location.search).has('payment')?'bookings':'discover'),[query,setQuery]=useState(''),[service,setService]=useState('all'),[sort,setSort]=useState('price'),[category,setCategory]=useState('all'),[maxPrice,setMaxPrice]=useState('all'),[duration,setDuration]=useState('all'),[advanced,setAdvanced]=useState(false),[selected,setSelected]=useState<Offer|null>(null),[slots,setSlots]=useState<{start:number;end:number}[]>([]),[loadingSlots,setLoadingSlots]=useState(false),[notice,setNotice]=useState(''),[chatId,setChatId]=useState(''),[demoRows,setDemoRows]=useState(()=>demoBookings().map((b,i)=>({...b,professional_name:'Prestador exemplo '+String.fromCharCode(65+i%3),customer_name:'Cliente exemplo'})));
 const user=p.demo?{id:'demo-customer',name:'Cliente exemplo',email:'cliente@example.invalid',phone:'Telefone demonstrativo'}:p.user;
 const offers=p.demo?demoOffers:p.offers,bookings=p.demo?demoRows:p.bookings;
 const filtered=filterOffers(offers,{query,category,service,maxPrice,duration,sort});
 const serviceOptions=p.services.filter(s=>category==='all'||categoryOf(s.id,s.name)===category);
 const activeCount=Number(service!=='all')+Number(maxPrice!=='all')+Number(duration!=='all');
 const reset=()=>{setQuery('');setCategory('all');setService('all');setMaxPrice('all');setDuration('all');setSort('price')};
 const chooseCategory=(value:string)=>{setCategory(value);setService('all')};
 useEffect(()=>{if(!selected)return;let active=true;setSlots([]);setNotice('');setLoadingSlots(true);
 if(p.demo){setSlots(Array.from({length:5},(_,i)=>{const start=Date.now()+(i+1)*86400000;return {start,end:start+selected.duration*60000}}));setLoadingSlots(false);return}
 apiFetch(`/api/professionals/${selected.professional_id}/availability?serviceId=${selected.service_id}&duration=${selected.duration}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(active)setSlots(data)}).catch(e=>{if(active)setNotice(e.message)}).finally(()=>{if(active)setLoadingSlots(false)});return()=>{active=false};
 },[selected,p.demo]);
 const open=(o:Offer)=>{if(!user){p.onRegister();return}setSelected(o)};
 return <div className="customer-shell"><header className="customer-header"><a className="logo" href="/">Help<span>.me</span></a><nav aria-label="Área do cliente">{[['discover','Explorar'],['bookings','Agendamentos'],['chat','Mensagens'],['profile','Minha conta']].filter(([key])=>user||key==='discover').map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>{if(!user&&key!=='discover'){p.onLogin();return}setTab(key)}}>{label}</button>)}</nav><div className="customer-session">{user?<><span>{user.name.split(' ')[0]}</span><button onClick={p.onLogout}>{p.demo?'Voltar':'Sair'}</button></>:<><button onClick={p.onLogin}>Entrar</button><button className="primary" onClick={p.onRegister}>Criar conta</button></>}</div></header><main className="customer-main">{p.demo&&<div className="demo-banner">Área demonstrativa: prestadores, serviços e mensagens fictícios. Alterações não são salvas nem enviadas a pessoas reais.</div>}{p.user&&!p.demo&&['suspended','rejected'].includes(p.user.accountStatus||'')&&<div className="notice">Conta {p.user.accountStatus==='suspended'?'suspensa':p.user.accountStatus==='rejected'?'recusada':'aguardando aprovação'}. Entre em contato com o suporte para regularizar o acesso.</div>}{p.catalogError&&<div role="alert" className="notice">{p.catalogError} <button disabled={p.catalogBusy} onClick={p.onRetryCatalog}>{p.catalogBusy?'Carregando…':'Tentar novamente'}</button></div>}{(p.error||notice)&&<div role="status" className="notice">{p.error||notice}</div>}
 {tab==='discover'&&<><section className="customer-intro"><div className="eyebrow">MAIS TEMPO PARA O QUE IMPORTA</div><h1>Uma ajuda para<br/><span>o seu dia a dia.</span></h1><p>Encontre serviços de limpeza e babás.<br/>Escolha o profissional e combine os detalhes por aqui.</p><div className="search-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input aria-label="Buscar serviço ou profissional" value={query} onChange={e=>setQuery(e.target.value)} placeholder="O que você precisa? Limpeza, babá…"/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}>×</button>}</div><div className="category-switch" aria-label="Categorias de serviços">{[['all','Todos','◎'],['cleaning','Limpeza','✦'],['childcare','Babás','♡']].map(([key,label,icon])=><button key={key} className={category===key?'selected':''} aria-pressed={category===key} onClick={()=>chooseCategory(key)}><span aria-hidden="true">{icon}</span>{label}</button>)}</div></section>
 <section className="discovery-content"><div className="directory-title"><div><h2>{category==='cleaning'?'Serviços de limpeza':category==='childcare'?'Cuidado para os pequenos':'Encontre sua próxima ajuda'}</h2><span role="status" aria-live="polite">{filtered.length} {filtered.length===1?'oferta':'ofertas'}{p.demo?' de demonstração':''}</span></div><div className="result-controls"><button className={advanced?'filter-toggle active':'filter-toggle'} aria-expanded={advanced} aria-controls="search-filters" onClick={()=>setAdvanced(!advanced)}>Filtros{activeCount>0&&<b>{activeCount}</b>}</button><select aria-label="Ordenar resultados" value={sort} onChange={e=>setSort(e.target.value)}><option value="price">Menor preço</option><option value="priceDesc">Maior preço</option><option value="name">Nome do profissional</option></select></div></div>
 {advanced&&<div className="directory-filters" id="search-filters"><label>Tipo de serviço<select value={service} onChange={e=>setService(e.target.value)}><option value="all">Todos os tipos</option>{serviceOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Preço por hora<select value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}><option value="all">Qualquer valor</option><option value="30">Até R$ 30/h</option><option value="50">Até R$ 50/h</option><option value="100">Até R$ 100/h</option></select></label><label>Duração<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="all">Qualquer duração</option><option value="2">Até 2 horas</option><option value="4">Até 4 horas</option><option value="6">Até 6 horas</option></select></label><button onClick={reset}>Limpar filtros</button></div>}
 <div className="provider-cards">{filtered.map(o=><article className="provider-card" key={o.professional_id+o.service_id}><div className={'service-cover '+categoryOf(o.service_id,o.service_name)}><span aria-hidden="true">{categoryOf(o.service_id,o.service_name)==='childcare'?'♡':'✦'}</span><span className="badge">{p.demo?'Demonstração':'Perfil aprovado'}</span></div><div className="provider-card-body"><small className="service-category">{categoryOf(o.service_id,o.service_name)==='childcare'?'CUIDADO INFANTIL':'SERVIÇOS PARA SUA CASA'}</small><h3>{o.service_name}</h3><div className="professional-row"><Avatar photo={o.photo_url} name={o.professional_name}/><span>{o.professional_name}</span></div><Rating average={o.rating_average} count={o.review_count}/><button className="profile-link" onClick={()=>setPublicProfile(o)}>Ver perfil e avaliações</button><div className="offer-details"><span>◷ {o.duration/60} horas</span><span>Total sugerido: {money(hourlyTotal(o.price,o.duration))}</span></div><div className="offer-bottom"><div className="offer-price"><strong>{money(o.price)}</strong><span>por hora</span></div><button className="primary" onClick={()=>open(o)}>Ver horários <span aria-hidden="true">↗</span></button></div></div></article>)}</div>
 {!filtered.length&&<section className="panel empty search-empty"><span aria-hidden="true">⌕</span><h3>{offers.length?'Não encontramos ofertas com esses filtros':p.catalogError?'Ofertas indisponíveis no momento':'Novos profissionais em breve'}</h3><p>{offers.length?'Experimente ampliar o preço ou escolher outra categoria.':p.catalogError?'Use o botão Tentar novamente para consultar os prestadores disponíveis.':'As ofertas aparecem assim que profissionais aprovados configuram seus serviços.'}</p>{(query||category!=='all'||activeCount>0)&&<button onClick={reset}>Ver todos os serviços</button>}</section>}
 <section className="customer-help"><div><strong>Escolha. Agende. Converse.</strong><p>Você solicita um horário e combina os detalhes no chat com o profissional.</p></div><span aria-hidden="true">↗</span></section></section></>}
 {tab==='bookings'&&<>{paymentReturn&&<div className="notice" role="status">{returnRow?.payment==='paid'?'Pagamento confirmado! Seu pedido está atualizado.':paymentReturn==='cancel'?'Você voltou do checkout. Consulte o status do pedido e continue o pagamento quando desejar.':'Aguardando confirmação do pagamento. O status será atualizado após a confirmação do Stripe.'}</div>}<div className="dashboard-heading"><div><h1>Meus serviços</h1><p>Acompanhe solicitações, confirmações e serviços realizados.</p></div><button className="primary" onClick={()=>setTab('discover')}>Encontrar prestador</button></div><div className="customer-bookings">{bookings.map(b=><article className="panel" key={b.id}><div className="panel-heading"><h2>{b.service_name}</h2><span className={'status '+b.status}>{status[b.status]}</span></div><p><strong>{b.professional_name}</strong> · {date(b.start)}</p><p>{b.address||'Endereço informado no pedido'}</p><div className="booking-bottom"><strong>{money(b.price)}</strong><span className="badge">{b.payment==='paid'?'Pagamento confirmado':'Pagamento pendente'}</span><button onClick={()=>{setChatId(b.id);setTab('chat')}}>Conversar</button>{canPay(b)&&<button className="primary" disabled={p.busy} onClick={()=>setPaying(b)}>Pagar serviço</button>}{['requested','accepted'].includes(b.status)&&!b.session_id&&b.payment!=='paid'&&b.start>Date.now()&&<button disabled={p.busy} onClick={()=>{if(p.demo){setDemoRows(prev=>prev.map(x=>x.id===b.id?{...x,status:'cancelled'}:x));return}p.onCancel(b.id).catch(e=>setNotice(e.message))}}>Cancelar pedido</button>}</div>{b.status==='completed'&&(reviewed.includes(b.id)?<p className="rating-summary">Você já avaliou este serviço.</p>:reviewsLoaded&&<><button className="profile-link" onClick={()=>setReviewing(reviewing===b.id?'':b.id)}>Avaliar serviço</button>{reviewing===b.id&&<ReviewForm bookingId={b.id} demo={p.demo} onDone={()=>{setReviewed(prev=>[...prev,b.id]);setReviewing('');setNotice(p.demo?'Avaliação demonstrativa. Não foi publicada.':'Avaliação publicada. Obrigado por compartilhar sua experiência.')}}/>}</>)}</article>)}</div>{!bookings.length&&<div className="panel empty"><h2>Seu primeiro serviço começa aqui</h2><p>Encontre um prestador e solicite um horário.</p></div>}</>}
 {tab==='chat'&&<><div className="dashboard-heading"><div><h1>Suas conversas</h1><p>Combine os detalhes com o prestador do seu serviço.</p></div></div><ServiceChat key={chatId||'customer-chat'} initialBooking={chatId} bookings={bookings} userId={user?.id||''} role="customer" demo={p.demo}/></>}
 {tab==='profile'&&<section className="panel customer-profile"><h1>Minha conta</h1><dl><dt>Nome</dt><dd>{user?.name}</dd><dt>Email</dt><dd>{user?.email||'Não informado'}</dd><dt>Telefone</dt><dd>{user?.phone||'Não informado'}</dd></dl><p>O endereço é informado em cada solicitação e mostrado ao prestador após o aceite.</p></section>}
 {selected&&<section className="booking-overlay"><div className="booking-dialog" role="dialog" aria-modal="true" aria-label="Solicitar serviço" onKeyDown={e=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),select,input'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><button autoFocus aria-label="Fechar solicitação" className="detail-close" onClick={()=>setSelected(null)}>×</button><span className="badge">{selected.professional_name}</span><h2>{selected.service_name}</h2><p>{money(selected.price)} por hora · <strong>Total: {money(hourlyTotal(selected.price,selected.duration))}</strong></p><label>Horas de serviço<select value={selected.duration} onChange={e=>setSelected({...selected,duration:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i} value={(i+1)*30}>{(i+1)/2} horas</option>)}</select></label>{notice&&<div className="notice" role="alert">{notice}</div>}{loadingSlots?<p role="status">Consultando horários…</p>:slots.length?<form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(p.demo){const start=Number(f.start);setDemoRows(prev=>[{id:'demo-request-'+crypto.randomUUID(),professional_name:selected.professional_name,customer_name:'Cliente exemplo',service_name:selected.service_name,start,end:start+selected.duration*60000,price:hourlyTotal(selected.price,selected.duration),status:'requested',payment:'unpaid',address:String(f.address),session_id:null},...prev]);setSelected(null);setTab('bookings');setNotice('Pedido demonstrativo criado. Não será enviado ou salvo.');return}p.onBook({professionalId:selected.professional_id,serviceId:selected.service_id,duration:selected.duration,start:new Date(Number(f.start)).toISOString(),address:f.address,requestKey:crypto.randomUUID()}).then(()=>{setSelected(null);setTab('bookings');setNotice('Solicitação enviada. O chat já está disponível.')}).catch(e=>setNotice(e.message))}}><label>Horário disponível<select name="start" required>{slots.map(s=><option key={s.start} value={s.start}>{date(s.start)} · Brasília</option>)}</select></label><label>Endereço completo<input name="address" minLength={10} maxLength={500} required placeholder="Rua, número, bairro e cidade"/></label><p>O prestador precisará aceitar sua solicitação. O pagamento fica disponível após o aceite.</p><button className="primary" disabled={p.busy}>Solicitar serviço</button></form>:<p>Nenhum horário disponível nos próximos 60 dias. Tente outro prestador.</p>}<button onClick={()=>setSelected(null)}>Voltar à busca</button></div></section>}
 {paying&&<Checkout booking={bookings.find(b=>b.id===paying.id)||paying} configured={p.stripe} busy={p.busy} demo={p.demo} onPay={p.onPay} onClose={()=>setPaying(null)}/>}
 {publicProfile&&<ProfileDialog id={publicProfile.professional_id} name={publicProfile.professional_name} demo={p.demo} onClose={()=>setPublicProfile(null)}/>}
 <footer>Help.me · Intermediação de serviços · Maravilha/SC</footer></main></div>
}

function bookingsForReturn(p:Props,id:string|null){return id?p.bookings.find(b=>b.id===id):undefined}
