import {useEffect,useState} from 'react';
import ServiceChat from '../../components/ServiceChat';
import {demoBookings,formatMoney as money,zone} from '../professional-dashboard/model';
import './customer.css';
type Offer={professional_id:string;service_id:string;professional_name:string;service_name:string;price:number;duration:number};
type Booking={id:string;service_name:string;professional_name:string;customer_name:string;status:string;payment:string;start:number;price:number;address:string|null;session_id:string|null};
type Props={user:{id:string;name:string;email?:string;phone?:string;approved?:boolean;accountStatus?:string}|null;offers:Offer[];bookings:Booking[];services:{id:string;name:string}[];busy:boolean;error:string;stripe:boolean;demo?:boolean;onRegister:()=>void;onLogin:()=>void;onLogout:()=>void;onBook:(input:unknown)=>Promise<void>;onCancel:(id:string)=>Promise<void>;onPay:(id:string)=>Promise<void>};
const date=(n:number)=>new Intl.DateTimeFormat('pt-BR',{timeZone:zone,day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(n);
const demoOffers:Offer[]=[{professional_id:'demo-p1',service_id:'residential',professional_name:'Prestador exemplo A',service_name:'Limpeza residencial',price:18000,duration:240},{professional_id:'demo-p2',service_id:'deep',professional_name:'Prestador exemplo B',service_name:'Limpeza pesada',price:26000,duration:360},{professional_id:'demo-p3',service_id:'residential',professional_name:'Prestador exemplo C',service_name:'Limpeza residencial',price:20000,duration:240}];
const status:Record<string,string>={requested:'Aguardando aceite',accepted:'Confirmado',completed:'Realizado',cancelled:'Cancelado',rejected:'Recusado'};
export default function CustomerArea(p:Props){
 const [tab,setTab]=useState('discover'),[query,setQuery]=useState(''),[service,setService]=useState('all'),[sort,setSort]=useState('name'),[selected,setSelected]=useState<Offer|null>(null),[slots,setSlots]=useState<{start:number;end:number}[]>([]),[loadingSlots,setLoadingSlots]=useState(false),[notice,setNotice]=useState(''),[chatId,setChatId]=useState(''),[demoRows,setDemoRows]=useState(()=>demoBookings().map((b,i)=>({...b,professional_name:'Prestador exemplo '+String.fromCharCode(65+i%3),customer_name:'Cliente exemplo'})));
 const user=p.demo?{id:'demo-customer',name:'Cliente exemplo',email:'cliente@example.invalid',phone:'Telefone demonstrativo'}:p.user;
 const offers=p.demo?demoOffers:p.offers,bookings=p.demo?demoRows:p.bookings;
 const filtered=offers.filter(o=>(service==='all'||o.service_id===service)&&(o.professional_name+' '+o.service_name).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:a.professional_name.localeCompare(b.professional_name,'pt-BR'));
 useEffect(()=>{if(!selected)return;let active=true;setSlots([]);setNotice('');setLoadingSlots(true);
 if(p.demo){setSlots(Array.from({length:5},(_,i)=>{const start=Date.now()+(i+1)*86400000;return {start,end:start+selected.duration*60000}}));setLoadingSlots(false);return}
 fetch(`/api/professionals/${selected.professional_id}/availability?serviceId=${selected.service_id}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(active)setSlots(data)}).catch(e=>{if(active)setNotice(e.message)}).finally(()=>{if(active)setLoadingSlots(false)});return()=>{active=false};
 },[selected,p.demo]);
 const open=(o:Offer)=>{if(!user){p.onRegister();return}setSelected(o)};
 return <div className="customer-shell"><header className="customer-header"><a className="logo" href="/">Help<span>.me</span></a><nav aria-label="Área do cliente">{[['discover','Encontrar prestadores'],['bookings','Meus serviços'],['chat','Mensagens'],['profile','Minha conta']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>{if(!user&&key!=='discover'){p.onLogin();return}setTab(key)}}>{label}</button>)}</nav><div className="customer-session">{user?<><span>{user.name.split(' ')[0]}</span><button onClick={p.onLogout}>{p.demo?'Voltar':'Sair'}</button></>:<><button onClick={p.onLogin}>Entrar</button><button className="primary" onClick={p.onRegister}>Criar conta</button></>}</div></header><main className="customer-main">{p.demo&&<div className="demo-banner">Área demonstrativa: prestadores, serviços e mensagens fictícios. Alterações não são salvas nem enviadas a pessoas reais.</div>}{p.user&&!p.demo&&!p.user.approved&&<div className="notice">Conta {p.user.accountStatus==='suspended'?'suspensa':p.user.accountStatus==='rejected'?'recusada':'aguardando aprovação'}. Solicitações e pagamentos exigem aprovação administrativa.</div>}{(p.error||notice)&&<div role="status" className="notice">{p.error||notice}</div>}
 {tab==='discover'&&<><section className="customer-intro"><div className="eyebrow">LIMPEZA EM MARAVILHA · SC</div><h1>Encontre quem cuida<br/>bem da sua casa.</h1><p>Compare os serviços, escolha um horário disponível e combine os detalhes com o prestador.</p></section><div className="directory-filters"><label>Nome ou serviço<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque um prestador ou serviço"/></label><label>Tipo de limpeza<select value={service} onChange={e=>setService(e.target.value)}><option value="all">Todos os serviços</option>{p.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Nome do prestador</option><option value="price">Menor preço</option></select></label></div><div className="directory-title"><h2>Prestadores e ofertas</h2><span>{filtered.length} opções {p.demo?'demonstrativas':''}</span></div><div className="provider-cards">{filtered.map(o=><article className="provider-card" key={o.professional_id+o.service_id}><div className="provider-card-top"><div className="provider-icon">{o.professional_name.charAt(0)}</div><span className="badge">{p.demo?'Exemplo':'Perfil aprovado'}</span></div><h3>{o.professional_name}</h3><p className="provider-location">Maravilha · Santa Catarina</p><div className="offer-service">{o.service_name}<small>{o.duration/60} horas de serviço</small></div><div className="offer-price"><strong>{money(o.price)}</strong><span>por serviço</span></div><button className="primary" onClick={()=>open(o)}>Ver horários e solicitar</button></article>)}</div>{!filtered.length&&<section className="panel empty"><h3>Nenhuma oferta encontrada</h3><p>{offers.length?'Tente outro nome ou tipo de serviço.':'Os prestadores aprovados aparecerão aqui assim que configurarem suas ofertas.'}</p></section>}<section className="customer-help"><strong>Do pedido à conversa, tudo em um só lugar.</strong><p>Após solicitar o serviço, o chat fica disponível para você e o prestador combinarem materiais, acesso ao local e prioridades da limpeza.</p></section></>}
 {tab==='bookings'&&<><div className="dashboard-heading"><div><h1>Meus serviços</h1><p>Acompanhe solicitações, confirmações e serviços realizados.</p></div><button className="primary" onClick={()=>setTab('discover')}>Encontrar prestador</button></div><div className="customer-bookings">{bookings.map(b=><article className="panel" key={b.id}><div className="panel-heading"><h2>{b.service_name}</h2><span className={'status '+b.status}>{status[b.status]}</span></div><p><strong>{b.professional_name}</strong> · {date(b.start)}</p><p>{b.address||'Endereço informado no pedido'}</p><div className="booking-bottom"><strong>{money(b.price)}</strong><span className="badge">{b.payment==='paid'?'Pagamento confirmado':'Pagamento pendente'}</span><button onClick={()=>{setChatId(b.id);setTab('chat')}}>Conversar</button>{b.status==='accepted'&&b.payment!=='paid'&&<button className="primary" disabled={p.busy||(!p.stripe&&!p.demo)} onClick={()=>{if(p.demo){setNotice('Checkout demonstrativo: nenhum pagamento será realizado neste agendamento.');return}p.onPay(b.id).catch(e=>setNotice(e.message))}}>{p.stripe?'Pagar pelo Stripe':'Pagamento indisponível'}</button>}{['requested','accepted'].includes(b.status)&&!b.session_id&&b.payment!=='paid'&&b.start>Date.now()&&<button disabled={p.busy} onClick={()=>{if(p.demo){setDemoRows(prev=>prev.map(x=>x.id===b.id?{...x,status:'cancelled'}:x));return}p.onCancel(b.id).catch(e=>setNotice(e.message))}}>Cancelar pedido</button>}</div></article>)}</div>{!bookings.length&&<div className="panel empty"><h2>Seu primeiro serviço começa aqui</h2><p>Encontre um prestador e solicite um horário.</p></div>}</>}
 {tab==='chat'&&<><div className="dashboard-heading"><div><h1>Suas conversas</h1><p>Combine os detalhes com o prestador do seu serviço.</p></div></div><ServiceChat key={chatId||'customer-chat'} initialBooking={chatId} bookings={bookings} userId={user?.id||''} role="customer" demo={p.demo}/></>}
 {tab==='profile'&&<section className="panel customer-profile"><h1>Minha conta</h1><dl><dt>Nome</dt><dd>{user?.name}</dd><dt>Email</dt><dd>{user?.email||'Não informado'}</dd><dt>Telefone</dt><dd>{user?.phone||'Não informado'}</dd></dl><p>O endereço é informado em cada solicitação e mostrado ao prestador após o aceite.</p></section>}
 {selected&&<section className="booking-overlay"><div className="booking-dialog" role="dialog" aria-modal="true" aria-label="Solicitar serviço" onKeyDown={e=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),select,input'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><button autoFocus aria-label="Fechar solicitação" className="detail-close" onClick={()=>setSelected(null)}>×</button><span className="badge">{selected.professional_name}</span><h2>{selected.service_name}</h2><p>{money(selected.price)} · {selected.duration/60} horas</p>{notice&&<div className="notice" role="alert">{notice}</div>}{loadingSlots?<p role="status">Consultando horários…</p>:slots.length?<form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(p.demo){const start=Number(f.start);setDemoRows(prev=>[{id:'demo-request-'+crypto.randomUUID(),professional_name:selected.professional_name,customer_name:'Cliente exemplo',service_name:selected.service_name,start,end:start+selected.duration*60000,price:selected.price,status:'requested',payment:'unpaid',address:String(f.address),session_id:null},...prev]);setSelected(null);setTab('bookings');setNotice('Pedido demonstrativo criado. Não será enviado ou salvo.');return}p.onBook({professionalId:selected.professional_id,serviceId:selected.service_id,start:new Date(Number(f.start)).toISOString(),address:f.address,requestKey:crypto.randomUUID()}).then(()=>{setSelected(null);setTab('bookings');setNotice('Solicitação enviada. O chat já está disponível.')}).catch(e=>setNotice(e.message))}}><label>Horário disponível<select name="start" required>{slots.map(s=><option key={s.start} value={s.start}>{date(s.start)} · Brasília</option>)}</select></label><label>Endereço completo<input name="address" minLength={10} maxLength={500} required placeholder="Rua, número, bairro e cidade"/></label><p>O prestador precisará aceitar sua solicitação. O pagamento fica disponível após o aceite.</p><button className="primary" disabled={p.busy}>Solicitar serviço</button></form>:<p>Nenhum horário disponível nos próximos 60 dias. Tente outro prestador.</p>}<button onClick={()=>setSelected(null)}>Voltar à busca</button></div></section>}
 <footer>Help.me · Intermediação de serviços · Maravilha/SC</footer></main></div>
}
