import {randomUUID} from 'node:crypto';
import {z} from 'zod';
export function installReputation(app,db,auth,fail){
 db.exec(`CREATE TABLE IF NOT EXISTS provider_profiles(professional_id TEXT PRIMARY KEY REFERENCES users(id),bio TEXT DEFAULT '',skills TEXT DEFAULT '',references_text TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS service_reviews(id TEXT PRIMARY KEY,booking_id TEXT UNIQUE REFERENCES bookings(id),customer_id TEXT REFERENCES users(id),professional_id TEXT REFERENCES users(id),rating INTEGER CHECK(rating BETWEEN 1 AND 5),comment TEXT,created_at INTEGER);CREATE INDEX IF NOT EXISTS review_provider ON service_reviews(professional_id,created_at);`);
 const schema=z.object({bio:z.string().trim().min(10).max(1500),skills:z.string().trim().min(3).max(1000),references:z.string().trim().max(1500).default('')});
 app.get('/api/provider-profile',(req,res,next)=>{try{const id=z.uuid().parse(req.query.professionalId);const p=db.prepare("SELECT name FROM users WHERE id=? AND role='professional' AND approved=1").get(id);if(!p)fail(404,'Perfil não encontrado.');const d=db.prepare('SELECT bio,skills,references_text AS "references" FROM provider_profiles WHERE professional_id=?').get(id)||{};const summary=db.prepare('SELECT round(avg(rating),1) rating_average,count(*) review_count FROM service_reviews WHERE professional_id=?').get(id);const reviews=db.prepare('SELECT r.id,r.rating,r.comment,r.created_at,u.name customer_name,s.name service_name FROM service_reviews r JOIN users u ON u.id=r.customer_id JOIN bookings b ON b.id=r.booking_id JOIN services s ON s.id=b.service_id WHERE r.professional_id=? ORDER BY r.created_at DESC LIMIT 100').all(id).map(r=>({...r,customer_name:r.customer_name.split(' ')[0]}));res.json({...p,...d,...summary,reviews})}catch(e){next(e)}});
 app.get('/api/provider-profile/me',auth,(req,res,next)=>{try{if(req.user.role!=='professional')fail(403,'Somente prestadores.');res.json(db.prepare('SELECT bio,skills,references_text AS "references" FROM provider_profiles WHERE professional_id=?').get(req.user.id)||{})}catch(e){next(e)}});
 app.post('/api/provider-profile/me',auth,(req,res,next)=>{try{if(req.user.role!=='professional')fail(403,'Somente prestadores.');const v=schema.parse(req.body);db.prepare('INSERT INTO provider_profiles VALUES(?,?,?,?) ON CONFLICT(professional_id) DO UPDATE SET bio=excluded.bio,skills=excluded.skills,references_text=excluded.references_text').run(req.user.id,v.bio,v.skills,v.references);res.json({ok:true})}catch(e){next(e)}});
 app.get('/api/reviews/mine',auth,(req,res)=>res.json(db.prepare('SELECT booking_id,rating,comment FROM service_reviews WHERE customer_id=?').all(req.user.id)));
 app.post('/api/reviews',auth,(req,res,next)=>{try{if(req.user.role!=='customer')fail(403,'Somente clientes podem avaliar.');const v=z.object({bookingId:z.uuid(),rating:z.number().int().min(1).max(5),comment:z.string().trim().min(3).max(1000)}).parse(req.body);const b=db.prepare('SELECT * FROM bookings WHERE id=? AND customer_id=?').get(v.bookingId,req.user.id);if(!b)fail(404,'Serviço não encontrado.');if(b.status!=='completed')fail(409,'A avaliação fica disponível após a conclusão do serviço.');if(db.prepare('SELECT id FROM service_reviews WHERE booking_id=?').get(b.id))fail(409,'Este serviço já foi avaliado.');db.prepare('INSERT INTO service_reviews VALUES(?,?,?,?,?,?,?)').run(randomUUID(),b.id,req.user.id,b.professional_id,v.rating,v.comment,Date.now());res.json({ok:true})}catch(e){next(e)}});
}
