import {apiFetch} from '../../lib/backend';
import {useEffect,useState} from 'react';
import './admin.css';
type Account={id:string;name:string;email:string;phone:string;role:string;accountStatus:string;isAdmin?:boolean};
type Booking={id:string;start:number;price:number;status:string;payment:string;service_name:string;customer_name:string;professional_name:string};
type Payment={session_id:string;booking_id:string;amount:number;confirmed_at:number;customer_name:string;professional_name:string;service_name:string;test_mode:number;platform_fee_amount?:number;provider_gross_amount?:number};
type Audit={id:string;actor_name:string;target_name:string;status:string;previous_status:string;note:string;created_at:number};
type Data={users:Account[];bookings:Booking[];payments:Payment[];audit:Audit[];services:{id:string;name:string;price:number;duration:number;offer_count:number}[];messageCount:number;stripeConfigured:boolean;testMode:boolean};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const date=(v:number)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
const labels:Record<string,string>={pending:'Pendente',approved:'Aprovado',rejected:'Recusado',suspended:'Suspenso',requested:'Solicitado',accepted:'Confirmado',completed:'Realizado',cancelled:'Cancelado',paid:'Pago',unpaid:'Não pago',customer:'Cliente',professional:'Prestador'};
function fixtures():Data{const now=Date.now();const users=[['c1','Marina Oliveira','customer','approved'],['c2','Lucas Almeida','customer','approved'],['p1','Ana Souza','professional','approved'],['p2','João Santos','professional','pending'],['c3','Beatriz Costa','customer','approved']].map(([id,name,role,accountStatus])=>({id,name,role,accountStatus,email:id+'@example.com',phone:'(49) 99999-0000'}));const bookings=Array.from({length:8},(_,i)=>({id:'demo-pedido-'+(i+1),start:now+(i-4)*86400000,price:i%2?26000:18000,status:i<4?'completed':i<6?'accepted':'requested',payment:i<4?'paid':'unpaid',service_name:i%2?'Limpeza pesada':'Limpeza residencial',customer_name:i%2?'Lucas Almeida':'Beatriz Costa',professional_name:'Ana Souza'}));return {users,bookings,payments:bookings.filter(b=>b.payment==='paid').map((b,i)=>({session_id:'cs_demo_'+i,booking_id:b.id,amount:b.price,confirmed_at:now-i*86400000,customer_name:b.customer_name,professional_name:b.professional_name,service_name:b.service_name,test_mode:1})),audit:[],services:[{id:'residential',name:'Limpeza residencial',price:18000,duration:240,offer_count:1},{id:'deep',name:'Limpeza pesada',price:26000,duration:360,offer_count:1}],messageCount:24,stripeConfigured:false,testMode:true}}
export default function AdminDashboard({demo,name,onLogout}:{demo:boolean;name:string;onLogout:()=>void}){
 const [data,setData]=useState<Data|null>(()=>demo?fixtures():null),[tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<Account|null>(null),[status,setStatus]=useState('approved'),[note,setNote]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 async function load(){setBusy(true);setError('');try{const r=await apiFetch('/api/admin');const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar o painel.')}finally{setBusy(false)}}
 useEffect(()=>{if(!demo)load()},[demo]);
 async function submit(){if(!review||!data)return;setBusy(true);setError('');try{if(demo){setData({...data,users:data.users.map(u=>u.id===review.id?{...u,accountStatus:status}:u),audit:[{id:crypto.randomUUID(),actor_name:'Administrador exemplo',target_name:review.name,status,previous_status:review.accountStatus,note,created_at:Date.now()},...data.audit]})}else{const r=await apiFetch('/api/admin/users/'+review.id+'/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note})});const v=await r.json();if(!r.ok)throw new Error(v.error);await load()}setReview(null);setNote('')}catch(e){setError(e instanceof Error?e.message:'Falha ao revisar conta.')}finally{setBusy(false)}}
 const match=(v:string)=>v.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
 const inRange=(v:number)=>{const d=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));return (!from||d>=from)&&(!to||d<=to)};
 const payments=data?.payments.filter(p=>inRange(p.confirmed_at)&&match(p.customer_name+' '+p.professional_name+' '+p.booking_id))||[];
 const pending=data?.users.filter(u=>u.role==='professional'&&u.accountStatus==='pending').length||0;
 function changeTab(t:string){setTab(t);setQuery('');setFilter('all');setFrom('');setTo('')}
 const titles:Record<string,string>={overview:'Visão geral',accounts:'Contas e aprovações',bookings:'Agendamentos',finance:'Movimentações financeiras',services:'Serviços',audit:'Histórico de ações'};
 return <div className="admin-shell"><aside className="admin-sidebar"><a className="logo" href="/">Help<span>.me</span></a><small>ADMINISTRAÇÃO</small><nav aria-label="Painel administrativo">{Object.entries(titles).map(([key,label],i)=><button key={key} className={tab===key?'selected':''} aria-current={tab===key?'page':undefined} onClick={()=>changeTab(key)}><span>{['◈','◎','▦','↗','☷','↺'][i]}</span>{label}{key==='accounts'&&pending>0&&<b>{pending}</b>}</button>)}</nav><div className="admin-user"><strong>{demo?'Administrador exemplo':name}</strong><small>Acesso administrativo</small><button onClick={onLogout}>{demo?'Voltar à plataforma':'Sair'}</button></div></aside><main className="admin-main"><header className="admin-heading"><div><small>HELP.ME / ADMINISTRAÇÃO</small><h1>{titles[tab]}</h1><p>Uma visão central da operação e das contas da plataforma.</p></div><button disabled={busy} onClick={()=>demo?setError('Dados demonstrativos. As alterações nesta sessão são temporárias.'):load()}>{busy?'Carregando…':'↻ Atualizar'}</button></header>{demo&&<div className="admin-banner">Prévia demonstrativa • dados fictícios • aprovações só alteram esta sessão.</div>}{error&&<div className="notice" role="alert">{error}</div>}{!data?<p>Carregando informações administrativas…</p>:<>
 {tab==='overview'&&<><div className="admin-stats">{[['Clientes',data.users.filter(u=>u.role==='customer').length,'Contas cadastradas'],['Prestadores',data.users.filter(u=>u.role==='professional').length,'Contas cadastradas'],['Aguardando aprovação',pending,'Somente prestadores'],['Pagamentos confirmados',money(data.payments.reduce((s,p)=>s+p.amount,0)),'Valor bruto • ambiente de teste']].map(([label,value,caption])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{caption}</span></article>)}</div><div className="admin-grid"><section className="admin-card"><h2>Operação da plataforma</h2>{['requested','accepted','completed','cancelled'].map(st=><div className="admin-metric" key={st}><span>{labels[st]}</span><strong>{data.bookings.filter(b=>b.status===st).length}</strong></div>)}<div className="admin-metric"><span>Mensagens trocadas</span><strong>{data.messageCount}</strong></div><button onClick={()=>changeTab('bookings')}>Ver todos os agendamentos →</button></section><section className="admin-card"><h2>Fila de aprovação</h2>{data.users.filter(u=>u.role==='professional'&&u.accountStatus==='pending').slice(0,5).map(u=><div className="admin-metric" key={u.id}><div><strong>{u.name}</strong><small>{labels[u.role]}</small></div><button onClick={()=>{setReview(u);setStatus('approved');setNote('')}}>Revisar</button></div>)}{!pending&&<p>Nenhuma conta aguardando aprovação.</p>}<button onClick={()=>changeTab('accounts')}>Gerenciar contas →</button></section></div><section className="admin-card"><h2>Pagamentos e integrações</h2><p>Stripe: {data.stripeConfigured?'checkout e webhook configurados em teste':'checkout e webhook do servidor ainda não configurados'}.</p><p>Comissões, tarifas, estornos e repasses bancários ainda não são sincronizados. Os valores confirmados representam pagamentos brutos dos clientes.</p></section></>}
 {['accounts','bookings','finance'].includes(tab)&&<div className="admin-toolbar"><input aria-label="Pesquisar" placeholder="Pesquisar por nome ou referência…" value={query} onChange={e=>setQuery(e.target.value)}/>{tab==='accounts'&&<select aria-label="Filtrar contas" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas as contas</option>{['pending','approved','rejected','suspended','customer','professional'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select>}{tab==='bookings'&&<select aria-label="Filtrar agendamentos" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option>{['requested','accepted','completed','cancelled','rejected'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select>}{tab==='finance'&&<><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></>}</div>}
 {tab==='accounts'&&<section className="admin-card admin-table" role="region" aria-label="Tabela administrativa" tabIndex={0}><table><thead><tr><th>Conta</th><th>Contato</th><th>Perfil</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{data.users.filter(u=>match(u.name+' '+u.email)&&(filter==='all'||filter===u.role||filter===u.accountStatus)).map(u=><tr key={u.id}><td>{u.name}{u.isAdmin&&<small>Administrador</small>}</td><td>{u.email}<small>{u.phone}</small></td><td>{labels[u.role]}</td><td><span className={'admin-badge '+u.accountStatus}>{labels[u.accountStatus]}</span></td><td><button disabled={u.isAdmin} onClick={()=>{setReview(u);setStatus(u.accountStatus==='approved'?'suspended':'approved');setNote('')}}>Revisar</button></td></tr>)}</tbody></table><p>{data.users.length} contas cadastradas na plataforma.</p></section>}
 {tab==='bookings'&&<section className="admin-card admin-table" role="region" aria-label="Tabela administrativa" tabIndex={0}><table><thead><tr><th>Serviço / referência</th><th>Cliente</th><th>Prestador</th><th>Data</th><th>Valor</th><th>Status</th><th>Pagamento</th></tr></thead><tbody>{data.bookings.filter(b=>match(b.customer_name+' '+b.professional_name+' '+b.id)&&(filter==='all'||b.status===filter)).map(b=><tr key={b.id}><td>{b.service_name}<small>{b.id}</small></td><td>{b.customer_name}</td><td>{b.professional_name}</td><td>{date(b.start)}</td><td>{money(b.price)}</td><td>{labels[b.status]}</td><td>{labels[b.payment]}</td></tr>)}</tbody></table>{!data.bookings.length&&<p>Nenhum agendamento registrado.</p>}</section>}
 {tab==='finance'&&<><div className="admin-stats"><article><small>Confirmado no período</small><strong>{money(payments.reduce((s,p)=>s+p.amount,0))}</strong><span>Bruto • {payments.length} pagamentos de teste</span></article><article><small>Agendamentos sem pagamento</small><strong>{money(data.bookings.filter(b=>b.payment!=='paid'&&['accepted','completed'].includes(b.status)).reduce((s,b)=>s+b.price,0))}</strong><span>Todos os períodos • não é saldo disponível</span></article><article><small>Comissão Help.me • 15%</small><strong>{money(payments.reduce((s,p)=>s+(p.platform_fee_amount||0),0))}</strong><span>Vinculada às cobranças diretas confirmadas</span></article><article><small>Depósitos bancários dos prestadores</small><strong>Não disponível</strong><span>Integração de repasses pendente</span></article></div><section className="admin-card admin-table" role="region" aria-label="Tabela administrativa" tabIndex={0}><h2>Pagamentos confirmados por webhook</h2><p>Modo de teste. A comissão das novas cobranças diretas é de 15%. Tarifas, estornos e depósitos bancários devem ser conferidos no Stripe.</p><table><thead><tr><th>Confirmação</th><th>Cliente / serviço</th><th>Prestador</th><th>Valor do serviço</th><th>Help.me • 15%</th><th>Prestador antes das tarifas</th><th>Referência Stripe</th></tr></thead><tbody>{payments.map(p=><tr key={p.session_id}><td>{date(p.confirmed_at)}</td><td>{p.customer_name}<small>{p.service_name}</small></td><td>{p.professional_name}</td><td>{money(p.amount)}</td><td>{p.platform_fee_amount!==undefined?money(p.platform_fee_amount):'Não informado'}</td><td>{p.provider_gross_amount!==undefined?money(p.provider_gross_amount):'Não informado'}</td><td>{p.session_id}<small>{p.test_mode?'Teste':'Produção'}</small></td></tr>)}</tbody></table>{!payments.length&&<p>Nenhum pagamento confirmado para esta seleção.</p>}</section></>}
 {tab==='services'&&<div className="admin-grid">{data.services.map(s=><section key={s.id} className="admin-card"><small>CATÁLOGO DA PLATAFORMA</small><h2>{s.name}</h2><strong>{money(s.price)}</strong><p>Preço de referência • prestadores definem suas ofertas.</p><div className="admin-metric"><span>Duração de referência</span><b>{s.duration} min</b></div><div className="admin-metric"><span>Ofertas cadastradas</span><b>{s.offer_count}</b></div></section>)}</div>}
 {tab==='audit'&&<section className="admin-card admin-table" role="region" aria-label="Tabela administrativa" tabIndex={0}><h2>Registro das revisões administrativas</h2><table><thead><tr><th>Data</th><th>Administrador</th><th>Conta</th><th>Alteração</th><th>Justificativa</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{date(a.created_at)}</td><td>{a.actor_name}</td><td>{a.target_name}</td><td>{labels[a.previous_status]} → {labels[a.status]}</td><td>{a.note}</td></tr>)}</tbody></table>{!data.audit.length&&<p>As próximas revisões de conta aparecerão aqui.</p>}<small>Até 200 ações recentes.</small></section>}
 </>}{review&&<div className="admin-overlay"><section className="admin-card" role="dialog" aria-modal="true" aria-labelledby="review-title"><h2 id="review-title">Revisar {review.name}</h2><p>{labels[review.role]} • {review.email}</p><form onSubmit={e=>{e.preventDefault();submit()}}><label>Novo status<select value={status} onChange={e=>setStatus(e.target.value)}>{(review.role==='customer'?['approved','rejected','suspended']:['approved','rejected','suspended','pending']).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Justificativa<textarea autoFocus required minLength={2} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre o motivo da decisão…"/></label><p>A suspensão bloqueia novas operações. Agendamentos e pagamentos existentes permanecem registrados.</p>{error&&<div role="alert">{error}</div>}<div className="admin-actions"><button type="button" disabled={busy} onClick={()=>setReview(null)}>Cancelar</button><button className="primary" disabled={busy||status===review.accountStatus}>{busy?'Salvando…':'Confirmar revisão'}</button></div></form></section></div>}</main></div>
}
