import {useEffect,useRef,useState} from 'react';
import {formatMoney as money,zone} from '../features/professional-dashboard/model';
import {canPay} from '../lib/checkout';
export type CheckoutBooking={id:string;service_name:string;professional_name:string;start:number;end?:number;billing_minutes?:number;hourly_rate?:number;price:number;status:string;payment:string};
export default function Checkout({booking,configured,busy,demo,onPay,onClose}:{booking:CheckoutBooking;configured:boolean;busy:boolean;demo?:boolean;onPay:(id:string)=>Promise<void>;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[error,setError]=useState('');
 useEffect(()=>{const el=dialog.current,previous=document.activeElement as HTMLElement|null;el?.showModal();return()=>{el?.close();previous?.focus()}},[]);
 const hours=booking.billing_minutes?booking.billing_minutes/60:booking.end?(booking.end-booking.start)/3600000:null;
 return <dialog ref={dialog} className="checkout-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose()}} aria-labelledby="checkout-title"><button className="detail-close" aria-label="Fechar pagamento" disabled={busy} onClick={onClose}>×</button><span className="eyebrow">PAGAMENTO DO SERVIÇO</span><h2 id="checkout-title">Revise seu pagamento</h2><p>Confira os detalhes antes de continuar.</p><dl className="checkout-summary"><dt>Serviço</dt><dd>{booking.service_name}</dd><dt>Prestador</dt><dd>{booking.professional_name}</dd><dt>Agendamento</dt><dd>{new Intl.DateTimeFormat('pt-BR',{timeZone:zone,dateStyle:'short',timeStyle:'short'}).format(booking.start)}</dd>{hours!==null&&<><dt>Horas contratadas</dt><dd>{hours.toLocaleString('pt-BR')} horas</dd></>}{booking.hourly_rate&&<><dt>Valor por hora</dt><dd>{money(booking.hourly_rate)}</dd></>}</dl><div className="checkout-total"><span>Total do serviço</span><strong>{money(booking.price)}</strong></div><p>O pagamento será processado pelo Stripe na conta do prestador. Você escolherá uma das formas de pagamento disponíveis na próxima tela.</p>{demo?<div className="notice">Demonstração: nenhum pagamento será realizado.</div>:!configured?<div className="notice" role="status">Os pagamentos estão aguardando ativação. Nenhum valor será cobrado enquanto a configuração não estiver concluída.</div>:<small>Seu pedido só será marcado como pago após a confirmação do Stripe.</small>}{error&&<div className="notice" role="alert">{error}</div>}<div className="actions"><button disabled={busy} onClick={onClose}>Voltar</button><button className="primary" disabled={busy||!canPay(booking)||(!configured&&!demo)} onClick={()=>{setError('');if(demo){setError('Esta prévia não abre uma cobrança real.');return}onPay(booking.id).catch(e=>setError(e instanceof Error?e.message:'Não foi possível abrir o pagamento.'))}}>{busy?'Abrindo pagamento…':demo?'Simular pagamento':'Continuar para pagamento'}</button></div><small>Dados do cartão são preenchidos no checkout seguro do Stripe.</small></dialog>;
}
