import {useEffect,useState} from 'react';
import {apiFetch} from '../lib/backend';
export default function ConnectPayments({approved,demo}:{approved:boolean;demo?:boolean}){
 const [state,setState]=useState<{configured:boolean;ready:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setError('');try{const r=await apiFetch('/api/connect/status');const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d)}catch(e){setError(e instanceof Error?e.message:'Não foi possível verificar a conta.')}}
 useEffect(()=>{if(approved&&!demo)refresh()},[approved,demo]);
 async function onboard(){setBusy(true);setError('');try{const r=await apiFetch('/api/connect/onboard',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.error);location.assign(d.url)}catch(e){setError(e instanceof Error?e.message:'Não foi possível conectar a conta.')}finally{setBusy(false)}}
 return <section className="panel"><h2>Receber pagamentos</h2><p>O cliente paga diretamente na sua conta Stripe. A Help.me recebe 15% de intermediação; sua parte é 85%, com as tarifas Stripe descontadas dela.</p>{demo?<p>Demonstração: nenhum cadastro bancário será realizado.</p>:!approved?<p>Seu perfil precisa ser aprovado antes de habilitar os pagamentos.</p>:<><p>{state?.ready?'Conta habilitada para cobrança. Consulte saldo, pendências e repasses no Stripe.':state?.configured?'Complete seu cadastro no Stripe para receber pelos serviços.':'A configuração de pagamentos da plataforma ainda está pendente.'}</p>{error&&<div role="alert" className="notice">{error}</div>}<div className="actions"><button className="primary" disabled={busy||!state?.configured} onClick={onboard}>{busy?'Aguarde…':state?.ready?'Atualizar cadastro Stripe':'Conectar conta de pagamentos'}</button><button onClick={refresh}>Verificar conta</button>{state?.ready&&<a href="https://dashboard.stripe.com" target="_blank" rel="noreferrer">Abrir Stripe ↗</a>}</div></>}<small>O crédito na conta Stripe e o depósito no banco são etapas distintas. Prazos e pendências são informados pelo Stripe.</small></section>
}
