import ProfilePhoto,{Avatar} from './ProfilePhoto';
import {useEffect,useState} from 'react';
import {apiFetch} from '../lib/backend';
export type Profile={photo_url?:string;name?:string;bio?:string;skills?:string;references?:string;rating_average?:number|null;review_count?:number;reviews?:{id:string;rating:number;comment:string;customer_name:string;service_name:string;created_at:number}[]};
export async function reputation(path:string,body?:unknown){const r=await apiFetch('/api'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error);return data}
export function Rating({average,count=0}:{average?:number|null;count?:number}){return <div className="rating-summary">{count>0&&average!=null?<><span className="stars" aria-hidden="true">★</span><strong>{Number(average).toLocaleString('pt-BR',{maximumFractionDigits:1,minimumFractionDigits:1})} / 5</strong><span>({count} {count===1?'avaliação':'avaliações'})</span></>:<span>Ainda sem avaliações</span>}</div>}
export function ProfileDialog({id,name,demo,onClose}:{id:string;name:string;demo?:boolean;onClose:()=>void}){
 const [profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;if(demo){setProfile({name,bio:'Perfil demonstrativo. Profissional com experiência em serviços para o dia a dia.',skills:'Organização, atenção aos detalhes e pontualidade.',references:'Experiências ilustrativas para conhecer a plataforma.',review_count:0,reviews:[]});return}reputation('/provider-profile?professionalId='+encodeURIComponent(id)).then(v=>{if(active)setProfile(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id,name,demo]);
 return <div className="booking-overlay"><section className="booking-dialog" role="dialog" aria-modal="true" aria-labelledby="public-profile-title" onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button,a[href]'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><button className="detail-close" autoFocus aria-label="Fechar perfil" onClick={onClose}>×</button><Avatar photo={profile?.photo_url} name={name} className="profile-photo-large"/><h2 id="public-profile-title">{name}</h2>{error&&<p role="alert">{error}</p>}{!profile&&!error&&<p role="status">Carregando perfil…</p>}{profile&&<><Rating average={profile.rating_average} count={profile.review_count}/>{[['Apresentação',profile.bio],['Habilidades',profile.skills],['Referências e experiências',profile.references]].map(([label,value])=><div className="profile-section" key={label}><h3>{label}</h3><p>{value||'Ainda não informado pelo prestador.'}</p></div>)}<h3>Avaliações de serviços concluídos</h3>{!profile.reviews?.length&&<p>Este prestador ainda não recebeu avaliações.</p>}{profile.reviews?.map(r=><article className="review-comment" key={r.id}><div><span className="stars" aria-label={r.rating+' de 5 estrelas'}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><strong>{r.customer_name}</strong></div><p>{r.comment}</p><small>{r.service_name} · {new Date(r.created_at).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></article>)}</>}<button onClick={onClose}>Voltar à busca</button></section></div>
}
export function ProfileEditor({demo}:{demo?:boolean}){
 const [profile,setProfile]=useState<Profile>({bio:'',skills:'',references:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!demo);
 useEffect(()=>{if(demo)return;let active=true;reputation('/provider-profile/me').then(v=>{if(active)setProfile(v)}).catch(e=>{if(active)setMessage(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[demo]);
 return <section className="panel"><h2>Meu perfil público</h2><p>Apresente sua experiência para quem está procurando um prestador.</p>{message&&<p className="notice" role="status">{message}</p>}{loading?<p role="status">Carregando perfil…</p>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{if(!demo)await reputation('/provider-profile/me',profile);setMessage(demo?'Perfil demonstrativo. Nada foi publicado.':'Perfil atualizado.')}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}}><ProfilePhoto value={profile.photo_url||''} onChange={photo_url=>setProfile({...profile,photo_url})}/>{[['bio','Apresentação',1500],['skills','Habilidades',1000],['references','Referências e experiências',1500]].map(([key,label,max])=><label key={key}>{label}<textarea required={key!=='references'} minLength={key==='bio'?10:key==='skills'?3:0} maxLength={Number(max)} value={String(profile[key as keyof Profile]||'')} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar perfil'}</button></form>}</section>
}
export function ReviewForm({bookingId,demo,onDone}:{bookingId:string;demo?:boolean;onDone:()=>void}){
 const [rating,setRating]=useState(0),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <form className="review-form" onSubmit={async e=>{e.preventDefault();if(!rating){setMessage('Escolha de 1 a 5 estrelas.');return}setBusy(true);try{if(!demo)await reputation('/reviews',{bookingId,rating,comment});onDone()}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível avaliar.')}finally{setBusy(false)}}}><h3>Como foi o serviço?</h3><fieldset className="star-picker"><legend>Sua nota de 1 a 5 estrelas</legend>{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name={'rating-'+bookingId} value={n} checked={rating===n} onChange={()=>setRating(n)} required/><span className={n<=rating?'stars':''} aria-hidden="true">★</span><span className="sr-only">{n} {n===1?'estrela':'estrelas'}</span></label>)}</fieldset><label>Comentário sobre a qualidade do serviço<textarea value={comment} onChange={e=>setComment(e.target.value)} minLength={3} maxLength={1000} required placeholder="Conte como foi sua experiência."/></label><small>Seu primeiro nome, nota e comentário ficarão públicos no perfil do prestador.</small>{message&&<p role="alert">{message}</p>}<button className="primary" disabled={busy||!rating}>{busy?'Enviando…':demo?'Simular avaliação':'Publicar avaliação'}</button></form>
}
