import {apiFetch} from '../lib/backend';
import {useEffect,useRef,useState} from 'react';
export type Conversation={id:string;customer_name:string;professional_name:string;service_name:string;status:string};
type Message={seq:number;id:string;booking_id:string;sender_id:string;body:string;created_at:number};
type Props={bookings:Conversation[];userId:string;role:'customer'|'professional';demo?:boolean;initialBooking?:string};
const time=(n:number)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(n);
export default function ServiceChat({bookings,userId,role,demo,initialBooking}:Props){
 const [selected,setSelected]=useState(initialBooking||bookings[0]?.id||''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[loading,setLoading]=useState(false);const end=useRef<HTMLDivElement>(null),cursor=useRef(0),pending=useRef<{body:string;id:string}|null>(null);
 const thread=bookings.find(b=>b.id===selected);const demoThreads=useRef<Record<string,Message[]>>({});
 useEffect(()=>{if(!selected&&bookings.length)setSelected(bookings[0].id)},[bookings,selected]);
 useEffect(()=>{let active=true;cursor.current=0;setMessages([]);setError('');setDraft('');pending.current=null;
 if(demo){setMessages(demoThreads.current[selected]||[{seq:1,id:'demo-first',booking_id:selected,sender_id:role==='customer'?'demo-professional':'demo-customer',body:'Olá! Podemos combinar os detalhes da limpeza por aqui. Esta é uma conversa demonstrativa.',created_at:Date.now()-3600000}]);return}
 async function load(){if(!selected||document.hidden)return;setLoading(true);try{const r=await apiFetch(`/api/bookings/${selected}/messages?after=${cursor.current}`);const data=await r.json();if(!r.ok)throw new Error(data.error);if(active){if(data.length){cursor.current=Math.max(cursor.current,...data.map((x:Message)=>x.seq));setMessages(prev=>{const all=new Map(prev.map(x=>[x.id,x]));data.forEach((x:Message)=>all.set(x.id,x));return [...all.values()].sort((a,b)=>a.seq-b.seq)})}setError('')}}catch(e){if(active)setError(e instanceof Error?e.message:'Conversa indisponível.')}finally{if(active)setLoading(false)}}
 load();const timer=setInterval(load,4000);return()=>{active=false;clearInterval(timer)};
 },[selected,demo,role]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages]);
 async function send(){const body=draft.trim();if(!body||sending)return;setSending(true);setError('');const conversation=selected;const key=pending.current?.body===body?pending.current.id:crypto.randomUUID();pending.current={body,id:key};try{let item:Message;if(demo){item={seq:(messages.at(-1)?.seq||0)+1,id:key,booking_id:conversation,sender_id:userId,body,created_at:Date.now()}}else{const r=await apiFetch(`/api/bookings/${conversation}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,clientMessageId:key})});item=await r.json();if(!r.ok)throw new Error((item as unknown as {error:string}).error)}setMessages(prev=>prev.some(x=>x.id===item.id)?prev:[...prev,item].sort((a,b)=>a.seq-b.seq));if(demo)demoThreads.current[conversation]=[...messages,item];setDraft('');pending.current=null}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar. Seu texto foi preservado.')}finally{setSending(false)}}
 return <section className="service-chat"><aside className="chat-threads"><h2>Conversas</h2><p>Uma conversa por agendamento.</p>{bookings.map(b=><button disabled={sending} className={selected===b.id?'selected':''} key={b.id} onClick={()=>setSelected(b.id)}><strong>{role==='customer'?b.professional_name:b.customer_name}</strong><small>{b.service_name}</small></button>)}{!bookings.length&&<p>Solicite um serviço para iniciar uma conversa.</p>}</aside><div className="chat-room">{thread?<><div className="chat-title"><div className="avatar">{(role==='customer'?thread.professional_name:thread.customer_name).charAt(0)}</div><div><strong>{role==='customer'?thread.professional_name:thread.customer_name}</strong><small>{thread.service_name}</small></div><span className="badge">{demo?'Demonstração':'Conversa privada'}</span></div><div className="chat-messages" role="log" aria-live="polite" aria-label="Mensagens da conversa">{messages.map(m=><div className={'chat-message '+(m.sender_id===userId?'mine':'')} key={m.id}><p>{m.body}</p><small>{m.sender_id===userId?'Você':'Participante'} · {time(m.created_at)}</small></div>)}{!messages.length&&<p className="empty">{loading?'Carregando conversa…':'Comece a conversa sobre seu serviço.'}</p>}<div ref={end}/></div>{error&&<div role="alert" className="notice">{error}</div>}<form className="chat-compose" onSubmit={e=>{e.preventDefault();send()}}><label className="sr-only" htmlFor="message-body">Sua mensagem</label><textarea id="message-body" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000} placeholder="Combine os detalhes do serviço…" rows={2} disabled={sending}/><button className="primary" disabled={sending||!draft.trim()}>{sending?'Enviando…':'Enviar'}</button></form><small className="chat-note">{demo?'As mensagens demonstrativas não são salvas e não chegam a um prestador real.':'Atualização a cada 4 segundos. Não compartilhe senhas ou dados de cartão.'}</small></>:<p className="empty">Selecione uma conversa.</p>}</div></section>
}
