import {useId,useState} from 'react';
import './charts.css';
type Point={label:string;value:number};
const currency=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
export function TrendChart({title,caption,points,money=false}:{title:string;caption:string;points:Point[];money?:boolean}){
 const id=useId().replaceAll(':',''),[active,setActive]=useState<number|null>(null);
 const total=points.reduce((sum,point)=>sum+point.value,0),max=Math.max(1,...points.map(point=>point.value));
 const format=money?currency:(v:number)=>String(v),coords=points.map((p,i)=>({x:40+i*520/Math.max(1,points.length-1),y:170-p.value/max*120}));
 const line=coords.map(p=>`${p.x},${p.y}`).join(' ');
 return <section className="insight-card"><div className="insight-heading"><div><h2>{title}</h2><p>{caption}</p></div><span className="insight-total">{format(total)}</span></div><div className="chart-readout" aria-live="polite">{active!==null?`Dias ${points[active].label}: ${format(points[active].value)}`:total?'Selecione uma semana para ver o valor.':'Nenhum registro neste período.'}</div><svg className="trend-svg" viewBox="0 0 600 210" role="img" aria-label={`${title}. Total ${format(total)}. Valores por semana disponíveis abaixo.`}><defs><linearGradient id={id} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#20B486" stopOpacity=".25"/><stop offset="100%" stopColor="#20B486" stopOpacity=".01"/></linearGradient></defs>{[50,110,170].map(y=><line key={y} x1="40" x2="560" y1={y} y2={y} stroke="#E4ECF2" strokeDasharray="4 5"/>)}<polygon points={`40,170 ${line} 560,170`} fill={`url(#${id})`}/><polyline points={line} fill="none" stroke="#15966F" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{coords.map((p,i)=><g key={points[i].label}><circle cx={p.x} cy={p.y} r={active===i?7:5} fill="#fff" stroke="#15966F" strokeWidth="3"/><text x={p.x} y="199" textAnchor="middle" fontSize="12" fill="#667784">{points[i].label}</text></g>)}</svg><div className="chart-weeks" style={{gridTemplateColumns:`repeat(${points.length},minmax(0,1fr))`}} aria-label="Valores por semana">{points.map((point,i)=><button key={point.label} aria-pressed={active===i} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)}><span>Dias {point.label}</span><strong>{format(point.value)}</strong></button>)}</div></section>;
}
export function StatusChart({items,caption}:{items:(Point&{color:string;key:string})[];caption:string}){
 const total=items.reduce((sum,item)=>sum+item.value,0);let offset=0;
 return <section className="insight-card"><div className="insight-heading"><div><h2>Serviços por situação</h2><p>{caption}</p></div></div><div className="status-chart"><div className="status-ring"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="46" fill="none" stroke="#EDF2F6" strokeWidth="12"/>{items.map(item=>{const length=total?item.value/total*289:0,previous=offset;offset+=length;return <circle key={item.key} cx="60" cy="60" r="46" fill="none" stroke={item.color} strokeWidth="12" strokeDasharray={`${length} ${289-length}`} strokeDashoffset={-previous} transform="rotate(-90 60 60)"/>})}</svg><div><strong>{total}</strong><span>serviços</span></div></div><ul className="status-breakdown">{items.map(item=><li key={item.key}><span><i style={{background:item.color}}/>{item.label}</span><strong>{item.value}<small>{total?Math.round(item.value/total*100):0}%</small></strong></li>)}</ul></div>{!total&&<p className="chart-empty">Seus agendamentos aparecerão aqui.</p>}</section>;
}
